// Code generated by workspace-cli-generator. DO NOT EDIT.

package scout_agent_api

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var setKafkaAddrRangeParams SetKafkaAddrRangeParams

var SetKafkaAddrRangeCmd = &cobra.Command{
	Use:   "set_kafka_addr_range",
	Short: "设置 kafka 地址",
	Long:  `设置 kafka 地址`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "ScoutAgentApiService.SetKafkaAddrRange", setKafkaAddrRangeParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// filter is object type, use JSON string
		var filterJSON string
		SetKafkaAddrRangeCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选器 (JSON, e.g. {\"agent_memory_rate\": [\"0.03298633\"], \"cpu\": [\"0.007942708\"], \"created_at\": [\"1664273285.232421\"], \"...\": \"...\"})")
		SetKafkaAddrRangeCmd.Flags().StringVar(&setKafkaAddrRangeParams.KafkaAddr, "kafka-addr", "", "kafka 地址")
		// select_filter is object type, use JSON string
		var selectFilterJSON string
		SetKafkaAddrRangeCmd.Flags().StringVar(&selectFilterJSON, "select-filter", "", "是否全选&主机ID (JSON, e.g. {\"select\": [{\"id\": 196}], \"select_all\": true})")
}


// SetKafkaAddrRangeParams 请求参数
type SetKafkaAddrRangeParams struct {
	Filter map[string]interface{} `json:"filter"` // 筛选器
	KafkaAddr string `json:"kafka_addr"` // kafka 地址
	SelectFilter map[string]interface{} `json:"select_filter"` // 是否全选&主机ID
}

