// Code generated by workspace-cli-generator. DO NOT EDIT.

package scout_agent_api

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var setResourceLimitParams SetResourceLimitParams

var SetResourceLimitCmd = &cobra.Command{
	Use:   "set_resource_limit",
	Short: "设置资源配额",
	Long:  `设置资源配额`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "ScoutAgentApiService.SetResourceLimit", setResourceLimitParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		SetResourceLimitCmd.Flags().IntVar(&setResourceLimitParams.Cpu, "cpu", 0, "CPU 占用率")
		SetResourceLimitCmd.Flags().IntVar(&setResourceLimitParams.Disk, "disk", 0, "磁盘使用上限，单位 KB/s")
		// filter is object type, use JSON string
		var filterJSON string
		SetResourceLimitCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选器 (JSON, e.g. {\"agent_memory_rate\": [\"0.03298633\"], \"cpu\": [\"0.007942708\"], \"created_at\": [\"1664273285.232421\"], \"...\": \"...\"})")
		SetResourceLimitCmd.Flags().IntVar(&setResourceLimitParams.Memory, "memory", 0, "内存占用量，单位 MB")
		SetResourceLimitCmd.Flags().IntVar(&setResourceLimitParams.Network, "network", 0, "网络使用上限，单位 KB/s")
		// select_filter is object type, use JSON string
		var selectFilterJSON string
		SetResourceLimitCmd.Flags().StringVar(&selectFilterJSON, "select-filter", "", "是否全选&主机ID (JSON, e.g. {\"select\": [{\"id\": 196}], \"select_all\": true})")
}


// SetResourceLimitParams 请求参数
type SetResourceLimitParams struct {
	Cpu int `json:"cpu"` // CPU 占用率
	Disk int `json:"disk"` // 磁盘使用上限，单位 KB/s
	Filter map[string]interface{} `json:"filter"` // 筛选器
	Memory int `json:"memory"` // 内存占用量，单位 MB
	Network int `json:"network"` // 网络使用上限，单位 KB/s
	SelectFilter map[string]interface{} `json:"select_filter"` // 是否全选&主机ID
}

