// Code generated by workspace-cli-generator. DO NOT EDIT.

package host_asset

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var editHostAttributeParams EditHostAttributeParams

var EditHostAttributeCmd = &cobra.Command{
	Use:   "edit_host_attribute",
	Short: "编辑主机属性信息",
	Long:  `编辑主机属性信息`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "HostAssetService.EditHostAttribute", editHostAttributeParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// attributes is complex type []map[string]interface{}, use JSON string
		var attributesJSON string
		EditHostAttributeCmd.Flags().StringVar(&attributesJSON, "attributes", "", "attributes (JSON, e.g. [{\"attr_name\": \"\", \"attr_type\": \"\", \"attr_value\": [\"\"]}])")
		EditHostAttributeCmd.Flags().Float64Var(&editHostAttributeParams.HostId, "host-id", 0, "主机 ID")
}


// EditHostAttributeParams 请求参数
type EditHostAttributeParams struct {
	Attributes []map[string]interface{} `json:"attributes"` // attributes
	HostId float64 `json:"host_id"` // 主机 ID
}

