// Code generated by workspace-cli-generator. DO NOT EDIT.

package report

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var listReportParams ListReportParams

var ListReportCmd = &cobra.Command{
	Use:   "list_report",
	Short: "获取报告列表",
	Long:  `获取报告列表`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "ReportService.ListReport", listReportParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		ListReportCmd.Flags().IntVar(&listReportParams.Count, "count", 20, "每页记录数量, 默认为 20")
		ListReportCmd.Flags().StringSliceVar(&listReportParams.Name, "name", nil, "报告名称")
		ListReportCmd.Flags().IntVar(&listReportParams.Offset, "offset", 0, "页偏移, 默认为 0")
		// order_by is object type, use JSON string
		var orderByJSON string
		ListReportCmd.Flags().StringVar(&orderByJSON, "order-by", "", "排序规则 (JSON, e.g. {\"column\": \"level\", \"order\": \"ASC\"})")
}


// ListReportParams 请求参数
type ListReportParams struct {
	Count int `json:"count"` // 每页记录数量, 默认为 20
	Name []string `json:"name"` // 报告名称
	Offset int `json:"offset"` // 页偏移, 默认为 0
	OrderBy map[string]interface{} `json:"order_by"` // 排序规则
}

