// Code generated by workspace-cli-generator. DO NOT EDIT.

package emergency_vuln_v1

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var createWhitelistParams CreateWhitelistParams

var CreateWhitelistCmd = &cobra.Command{
	Use:   "create_whitelist",
	Short: "生成应急漏洞白名单规则",
	Long:  `生成应急漏洞白名单规则`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "EmergencyVulnV1Service.CreateWhitelist", createWhitelistParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// select is complex type []map[string]interface{}, use JSON string
		var selectJSON string
		CreateWhitelistCmd.Flags().StringVar(&selectJSON, "select", "", "select (JSON, e.g. [{\"event_id\": 120, \"host_id\": 111, \"vuln_id\": 111}])")
		CreateWhitelistCmd.Flags().BoolVar(&createWhitelistParams.SelectAll, "select-all", false, "select_all")
		// whitelist is object type, use JSON string
		var whitelistJSON string
		CreateWhitelistCmd.Flags().StringVar(&whitelistJSON, "whitelist", "", "whitelist (JSON, e.g. {\"agent_range\": [1, 2, 3], \"builtin_id\": \"1\", \"business_group_range\": [1, 2, 3], \"...\": \"...\"})")
}


// CreateWhitelistParams 请求参数
type CreateWhitelistParams struct {
	Select []map[string]interface{} `json:"select"` // select
	SelectAll bool `json:"select_all"` // select_all
	Whitelist map[string]interface{} `json:"whitelist"` // whitelist
}

