// Code generated by workspace-cli-generator. DO NOT EDIT.

package asset_config

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var resetAssetCollectConfigParams ResetAssetCollectConfigParams

var ResetAssetCollectConfigCmd = &cobra.Command{
	Use:   "reset_asset_collect_config",
	Short: "重置资产采集设置",
	Long:  `重置资产采集设置`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "AssetConfigService.ResetAssetCollectConfig", resetAssetCollectConfigParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// rule is complex type []map[string]interface{}, use JSON string
		var ruleJSON string
		ResetAssetCollectConfigCmd.Flags().StringVar(&ruleJSON, "rule", "", "重置规则，未提交的规则将重置为默认值 (JSON, e.g. [{\"enable\": false, \"interval\": 0, \"type\": \"\"}])")
}


// ResetAssetCollectConfigParams 请求参数
type ResetAssetCollectConfigParams struct {
	Rule []map[string]interface{} `json:"rule"` // 重置规则，未提交的规则将重置为默认值
}

