// Code generated by workspace-cli-generator. DO NOT EDIT.

package detection_rule

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var enablementSensitivePortRuleParams EnablementSensitivePortRuleParams

var EnablementSensitivePortRuleCmd = &cobra.Command{
	Use:   "enablement_sensitive_port_rule",
	Short: "启禁用高危端口检测规则",
	Long:  `启禁用高危端口检测规则`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "DetectionRuleService.EnablementSensitivePortRule", enablementSensitivePortRuleParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		EnablementSensitivePortRuleCmd.Flags().BoolVar(&enablementSensitivePortRuleParams.Enable, "enable", false, "是否启用")
		// filter is object type, use JSON string
		var filterJSON string
		EnablementSensitivePortRuleCmd.Flags().StringVar(&filterJSON, "filter", "", "规则过滤器 (JSON, e.g. {\"custom_attr\": [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}], \"enable\": true, \"host_comment\": [\"主机备注\"], \"...\": \"...\"})")
}


// EnablementSensitivePortRuleParams 请求参数
type EnablementSensitivePortRuleParams struct {
	Enable bool `json:"enable"` // 是否启用
	Filter map[string]interface{} `json:"filter"` // 规则过滤器
}

