// Code generated by workspace-cli-generator. DO NOT EDIT.

package port_asset

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getPortAssetListByCmdParams GetPortAssetListByCmdParams

var GetPortAssetListByCmdCmd = &cobra.Command{
	Use:   "get_port_asset_list_by_cmd",
	Short: "进程名数据分组，按照指定条件获取端口资产",
	Long:  `进程名数据分组，按照指定条件获取端口资产`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "PortAssetService.GetPortAssetListByCmd", getPortAssetListByCmdParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		GetPortAssetListByCmdCmd.Flags().StringSliceVar(&getPortAssetListByCmdParams.Cmd, "cmd", nil, "IP")
		GetPortAssetListByCmdCmd.Flags().IntVar(&getPortAssetListByCmdParams.Count, "count", 20, "数量")
		// custom_attr is complex type []map[string]interface{}, use JSON string
		var customAttrJSON string
		GetPortAssetListByCmdCmd.Flags().StringVar(&customAttrJSON, "custom-attr", "", "主机业务属性 (JSON, e.g. [{\"attr_name\": \"负责人\", \"attr_value\": [\"David\"]}])")
		// filter is complex type []map[string]interface{}, use JSON string
		var filterJSON string
		GetPortAssetListByCmdCmd.Flags().StringVar(&filterJSON, "filter", "", "filter (JSON, e.g. [{\"cmd\": \"java\", \"id\": 151, \"ip\": \"::\", \"port\": 50002, \"protocol\": \"tcp\"}])")
		GetPortAssetListByCmdCmd.Flags().Float64SliceVar(&getPortAssetListByCmdParams.Gids, "gids", nil, "gids")
		GetPortAssetListByCmdCmd.Flags().StringSliceVar(&getPortAssetListByCmdParams.HostComment, "host-comment", nil, "主机备注")
		GetPortAssetListByCmdCmd.Flags().Float64SliceVar(&getPortAssetListByCmdParams.HostId, "host-id", nil, "主机 ID")
		GetPortAssetListByCmdCmd.Flags().StringSliceVar(&getPortAssetListByCmdParams.HostIp, "host-ip", nil, "主机 IP")
		GetPortAssetListByCmdCmd.Flags().StringSliceVar(&getPortAssetListByCmdParams.HostName, "host-name", nil, "主机名称")
		GetPortAssetListByCmdCmd.Flags().StringSliceVar(&getPortAssetListByCmdParams.HostState, "host-state", nil, "主机状态")
		GetPortAssetListByCmdCmd.Flags().StringSliceVar(&getPortAssetListByCmdParams.HostTags, "host-tags", nil, "主机标签")
		GetPortAssetListByCmdCmd.Flags().StringSliceVar(&getPortAssetListByCmdParams.Ip, "ip", nil, "IP")
		GetPortAssetListByCmdCmd.Flags().IntVar(&getPortAssetListByCmdParams.Offset, "offset", 0, "偏移量")
		GetPortAssetListByCmdCmd.Flags().Float64SliceVar(&getPortAssetListByCmdParams.Oid, "oid", nil, "机构 ID")
		// order_by is object type, use JSON string
		var orderByJSON string
		GetPortAssetListByCmdCmd.Flags().StringVar(&orderByJSON, "order-by", "", "排序规则 (JSON, e.g. {\"column\": \"level\", \"order\": \"ASC\"})")
		GetPortAssetListByCmdCmd.Flags().Float64SliceVar(&getPortAssetListByCmdParams.Pid, "pid", nil, "IP")
		GetPortAssetListByCmdCmd.Flags().StringSliceVar(&getPortAssetListByCmdParams.Port, "port", nil, "IP")
		GetPortAssetListByCmdCmd.Flags().StringSliceVar(&getPortAssetListByCmdParams.Protocol, "protocol", nil, "IP")
		GetPortAssetListByCmdCmd.Flags().BoolVar(&getPortAssetListByCmdParams.SelectAll, "select-all", false, "select_all")
		GetPortAssetListByCmdCmd.Flags().BoolVar(&getPortAssetListByCmdParams.SingletonPortProcess, "singleton-port-process", false, "单例网络应用")
		GetPortAssetListByCmdCmd.Flags().StringSliceVar(&getPortAssetListByCmdParams.UpdatedAt, "updated-at", nil, "IP")
		GetPortAssetListByCmdCmd.Flags().BoolSliceVar(&getPortAssetListByCmdParams.Visibility, "visibility", nil, "true")
}


// GetPortAssetListByCmdParams 请求参数
type GetPortAssetListByCmdParams struct {
	Cmd []string `json:"cmd"` // IP
	Count int `json:"count"` // 数量
	CustomAttr []map[string]interface{} `json:"custom_attr"` // 主机业务属性
	Filter []map[string]interface{} `json:"filter"` // filter
	Gids []float64 `json:"gids"` // gids
	HostComment []string `json:"host_comment"` // 主机备注
	HostId []float64 `json:"host_id"` // 主机 ID
	HostIp []string `json:"host_ip"` // 主机 IP
	HostName []string `json:"host_name"` // 主机名称
	HostState []string `json:"host_state"` // 主机状态
	HostTags []string `json:"host_tags"` // 主机标签
	Ip []string `json:"ip"` // IP
	Offset int `json:"offset"` // 偏移量
	Oid []float64 `json:"oid"` // 机构 ID
	OrderBy map[string]interface{} `json:"order_by"` // 排序规则
	Pid []float64 `json:"pid"` // IP
	Port []string `json:"port"` // IP
	Protocol []string `json:"protocol"` // IP
	SelectAll bool `json:"select_all"` // select_all
	SingletonPortProcess bool `json:"singleton_port_process"` // 单例网络应用
	UpdatedAt []string `json:"updated_at"` // IP
	Visibility []bool `json:"visibility"` // true
}

