// Code generated by workspace-cli-generator. DO NOT EDIT.

package firewall

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var deleteHostIsolateRuleParams DeleteHostIsolateRuleParams

var DeleteHostIsolateRuleCmd = &cobra.Command{
	Use:   "delete_host_isolate_rule",
	Short: "删除一键隔离失陷主机规则",
	Long:  `删除一键隔离失陷主机规则`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "FirewallService.DeleteHostIsolateRule", deleteHostIsolateRuleParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// filter is object type, use JSON string
		var filterJSON string
		DeleteHostIsolateRuleCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选器 (JSON, e.g. {\"created_at\": [\"\"], \"enable\": true, \"host_group\": [1], \"...\": \"...\"})")
}


// DeleteHostIsolateRuleParams 请求参数
type DeleteHostIsolateRuleParams struct {
	Filter map[string]interface{} `json:"filter"` // 筛选器
}

