// Code generated by workspace-cli-generator. DO NOT EDIT.

package firewall

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var deleteRuleParams DeleteRuleParams

var DeleteRuleCmd = &cobra.Command{
	Use:   "delete_rule",
	Short: "删除规则",
	Long:  `删除规则`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "FirewallService.DeleteRule", deleteRuleParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// filter is object type, use JSON string
		var filterJSON string
		DeleteRuleCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选器 (JSON, e.g. {\"action\": [\"ACCEPT\"], \"cidr\": [\"\"], \"created_at\": [\"\"], \"...\": \"...\"})")
}


// DeleteRuleParams 请求参数
type DeleteRuleParams struct {
	Filter map[string]interface{} `json:"filter"` // 筛选器
}

