// Code generated by workspace-cli-generator. DO NOT EDIT.

package firewall

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getHostIsolateRuleParams GetHostIsolateRuleParams

var GetHostIsolateRuleCmd = &cobra.Command{
	Use:   "get_host_isolate_rule",
	Short: "获取一键隔离失陷主机规则列表",
	Long:  `获取一键隔离失陷主机规则列表`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "FirewallService.GetHostIsolateRule", getHostIsolateRuleParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// filter is object type, use JSON string
		var filterJSON string
		GetHostIsolateRuleCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选器 (JSON, e.g. {\"created_at\": [\"\"], \"enable\": true, \"host_group\": [1], \"...\": \"...\"})")
		// page is object type, use JSON string
		var pageJSON string
		GetHostIsolateRuleCmd.Flags().StringVar(&pageJSON, "page", "", "分页器 (JSON, e.g. {\"count\": 20, \"offset\": 0, \"order\": {\"column\": \"level\", \"order\": \"ASC\"}})")
}


// GetHostIsolateRuleParams 请求参数
type GetHostIsolateRuleParams struct {
	Filter map[string]interface{} `json:"filter"` // 筛选器
	Page map[string]interface{} `json:"page"` // 分页器
}

