// Code generated by workspace-cli-generator. DO NOT EDIT.

package firewall

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getRuleParams GetRuleParams

var GetRuleCmd = &cobra.Command{
	Use:   "get_rule",
	Short: "获取规则列表",
	Long:  `获取规则列表`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "FirewallService.GetRule", getRuleParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// filter is object type, use JSON string
		var filterJSON string
		GetRuleCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选器 (JSON, e.g. {\"action\": [\"ACCEPT\"], \"cidr\": [\"\"], \"created_at\": [\"\"], \"...\": \"...\"})")
		// page is object type, use JSON string
		var pageJSON string
		GetRuleCmd.Flags().StringVar(&pageJSON, "page", "", "分页器 (JSON, e.g. {\"count\": 20, \"offset\": 0, \"order\": {\"column\": \"level\", \"order\": \"ASC\"}})")
}


// GetRuleParams 请求参数
type GetRuleParams struct {
	Filter map[string]interface{} `json:"filter"` // 筛选器
	Page map[string]interface{} `json:"page"` // 分页器
}

