// Code generated by workspace-cli-generator. DO NOT EDIT.

package firewall

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getConnectionRecordParams GetConnectionRecordParams

var GetConnectionRecordCmd = &cobra.Command{
	Use:   "get_connection_record",
	Short: "获取连接记录",
	Long:  `获取连接记录`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "FirewallService.GetConnectionRecord", getConnectionRecordParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// filter is object type, use JSON string
		var filterJSON string
		GetConnectionRecordCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选条件 (JSON, e.g. {\"conn_type\": [0.0], \"dest_cidr\": [\"192.168.1.2\"], \"group_ids\": [100, 101], \"...\": \"...\"})")
		// page is object type, use JSON string
		var pageJSON string
		GetConnectionRecordCmd.Flags().StringVar(&pageJSON, "page", "", "分页参数 (JSON, e.g. {\"count\": 20, \"offset\": 0, \"order\": {\"column\": \"level\", \"order\": \"ASC\"}})")
}


// GetConnectionRecordParams 请求参数
type GetConnectionRecordParams struct {
	Filter map[string]interface{} `json:"filter"` // 筛选条件
	Page map[string]interface{} `json:"page"` // 分页参数
}

