// Code generated by workspace-cli-generator. DO NOT EDIT.

package firewall

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getConnectionCollectRuleParams GetConnectionCollectRuleParams

var GetConnectionCollectRuleCmd = &cobra.Command{
	Use:   "get_connection_collect_rule",
	Short: "获取连接采集规则",
	Long:  `获取连接采集规则`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "FirewallService.GetConnectionCollectRule", getConnectionCollectRuleParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// filter is object type, use JSON string
		var filterJSON string
		GetConnectionCollectRuleCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选条件 (JSON, e.g. {\"created_at\": [\"xxxxxxxxx\"], \"enable\": true, \"host_ip\": [\"192.168.1.1\"], \"...\": \"...\"})")
		// page is object type, use JSON string
		var pageJSON string
		GetConnectionCollectRuleCmd.Flags().StringVar(&pageJSON, "page", "", "分页参数 (JSON, e.g. {\"count\": 20, \"offset\": 0, \"order\": {\"column\": \"level\", \"order\": \"ASC\"}})")
}


// GetConnectionCollectRuleParams 请求参数
type GetConnectionCollectRuleParams struct {
	Filter map[string]interface{} `json:"filter"` // 筛选条件
	Page map[string]interface{} `json:"page"` // 分页参数
}

