// Code generated by workspace-cli-generator. DO NOT EDIT.

package firewall

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getTopologyParams GetTopologyParams

var GetTopologyCmd = &cobra.Command{
	Use:   "get_topology",
	Short: "获取网络拓扑",
	Long:  `获取网络拓扑`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "FirewallService.GetTopology", getTopologyParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// filter is object type, use JSON string
		var filterJSON string
		GetTopologyCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选条件 (JSON, e.g. {\"access_count\": 0.0, \"conn_kind\": [0.0], \"conn_type\": [0.0], \"...\": \"...\"})")
}


// GetTopologyParams 请求参数
type GetTopologyParams struct {
	Filter map[string]interface{} `json:"filter"` // 筛选条件
}

