// Code generated by workspace-cli-generator. DO NOT EDIT.

package log_collect

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var createLogCollectParams CreateLogCollectParams

var CreateLogCollectCmd = &cobra.Command{
	Use:   "create_log_collect",
	Short: "创建日志采集",
	Long:  `创建日志采集`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "LogCollectService.CreateLogCollect", createLogCollectParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// account_change_log is object type, use JSON string
		var accountChangeLogJSON string
		CreateLogCollectCmd.Flags().StringVar(&accountChangeLogJSON, "account-change-log", "", "账号变更日志 (JSON, e.g. {\"enable\": false, \"exclude_rules\": [{\"method\": \"\", \"name\": \"\", \"username\": [\"...\"]}]})")
		CreateLogCollectCmd.Flags().StringVar(&createLogCollectParams.Addr, "addr", "", "地址")
		CreateLogCollectCmd.Flags().Float64SliceVar(&createLogCollectParams.AgentRange, "agent-range", nil, "主机范围")
		CreateLogCollectCmd.Flags().Float64SliceVar(&createLogCollectParams.BusinessGroupRange, "business-group-range", nil, "业务组范围")
		// dns_request_log is object type, use JSON string
		var dnsRequestLogJSON string
		CreateLogCollectCmd.Flags().StringVar(&dnsRequestLogJSON, "dns-request-log", "", "DNS 请求日志 (JSON, e.g. {\"enable\": false, \"exclude_rules\": [{\"keyword\": [\"...\"], \"method\": \"\", \"name\": \"\", \"suffix_domain\": [\"...\"]}]})")
		CreateLogCollectCmd.Flags().BoolVar(&createLogCollectParams.Enable, "enable", false, "是否启用")
		// file_change_log is object type, use JSON string
		var fileChangeLogJSON string
		CreateLogCollectCmd.Flags().StringVar(&fileChangeLogJSON, "file-change-log", "", "文件变更日志 (JSON, e.g. {\"enable\": false, \"rules\": [{\"enable\": false, \"exclude_keyword\": [\"...\"], \"name\": \"\", \"path\": \"\"}]})")
		CreateLogCollectCmd.Flags().BoolVar(&createLogCollectParams.Global, "global", false, "是否绑定全局探针")
		CreateLogCollectCmd.Flags().StringVar(&createLogCollectParams.MsgFormat, "msg-format", "", "消息格式")
		CreateLogCollectCmd.Flags().IntVar(&createLogCollectParams.Port, "port", 0, "端口")
		// port_listen_log is object type, use JSON string
		var portListenLogJSON string
		CreateLogCollectCmd.Flags().StringVar(&portListenLogJSON, "port-listen-log", "", "端口监听日志 (JSON, e.g. {\"enable\": false, \"exclude_rules\": [{\"method\": \"\", \"name\": \"\", \"path\": [\"...\"], \"port_range\": [\"...\"]}]})")
		// process_start_log is object type, use JSON string
		var processStartLogJSON string
		CreateLogCollectCmd.Flags().StringVar(&processStartLogJSON, "process-start-log", "", "进程启动日志 (JSON, e.g. {\"enable\": false, \"exclude_rules\": [{\"method\": \"\", \"name\": \"\", \"path\": [\"...\"]}]})")
		CreateLogCollectCmd.Flags().StringVar(&createLogCollectParams.Protocol, "protocol", "", "协议")
		CreateLogCollectCmd.Flags().StringVar(&createLogCollectParams.Remark, "remark", "", "备注")
		// system_login_log is object type, use JSON string
		var systemLoginLogJSON string
		CreateLogCollectCmd.Flags().StringVar(&systemLoginLogJSON, "system-login-log", "", "系统登陆日志 (JSON, e.g. {\"enable\": false, \"exclude_rules\": [{\"auth_method\": \"\", \"method\": \"\", \"name\": \"\", \"source_ip\": [\"...\"], \"username\": [\"...\"]}]})")
		// tcp_dial_log is object type, use JSON string
		var tcpDialLogJSON string
		CreateLogCollectCmd.Flags().StringVar(&tcpDialLogJSON, "tcp-dial-log", "", "TCP 连接日志 (JSON, e.g. {\"enable\": false, \"exclude_rules\": [{\"method\": \"\", \"name\": \"\", \"target_cidr\": [\"...\"], \"target_port_range\": [\"...\"]}]})")
}


// CreateLogCollectParams 请求参数
type CreateLogCollectParams struct {
	AccountChangeLog map[string]interface{} `json:"account_change_log"` // 账号变更日志
	Addr string `json:"addr"` // 地址
	AgentRange []float64 `json:"agent_range"` // 主机范围
	BusinessGroupRange []float64 `json:"business_group_range"` // 业务组范围
	DnsRequestLog map[string]interface{} `json:"dns_request_log"` // DNS 请求日志
	Enable bool `json:"enable"` // 是否启用
	FileChangeLog map[string]interface{} `json:"file_change_log"` // 文件变更日志
	Global bool `json:"global"` // 是否绑定全局探针
	MsgFormat string `json:"msg_format"` // 消息格式
	Port int `json:"port"` // 端口
	PortListenLog map[string]interface{} `json:"port_listen_log"` // 端口监听日志
	ProcessStartLog map[string]interface{} `json:"process_start_log"` // 进程启动日志
	Protocol string `json:"protocol"` // 协议
	Remark string `json:"remark"` // 备注
	SystemLoginLog map[string]interface{} `json:"system_login_log"` // 系统登陆日志
	TcpDialLog map[string]interface{} `json:"tcp_dial_log"` // TCP 连接日志
}

