// Code generated by workspace-cli-generator. DO NOT EDIT.

package agent_module

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var operateVeinmindAgentParams OperateVeinmindAgentParams

var OperateVeinmindAgentCmd = &cobra.Command{
	Use:   "operate_veinmind_agent",
	Short: "操作探针模块",
	Long:  `操作探针模块`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "AgentModuleService.OperateVeinmindAgent", operateVeinmindAgentParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// filter is object type, use JSON string
		var filterJSON string
		OperateVeinmindAgentCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选器 (JSON, e.g. {\"agent_install_plan_id\": [1, 2], \"agent_mem_size\": [\"1GB\"], \"agent_memory_rate\": [\"0.03298633\"], \"...\": \"...\"})")
		// operation_data is object type, use JSON string
		var operationDataJSON string
		OperateVeinmindAgentCmd.Flags().StringVar(&operationDataJSON, "operation-data", "", "更新||卸载||安装探针指定模块 (JSON, e.g. {\"agent_type\": \"vm_protect_agent\", \"operation\": \"install\"})")
		// select_filter is object type, use JSON string
		var selectFilterJSON string
		OperateVeinmindAgentCmd.Flags().StringVar(&selectFilterJSON, "select-filter", "", "是否全选&主机ID (JSON, e.g. {\"select\": [{\"id\": 196}], \"select_all\": true})")
}


// OperateVeinmindAgentParams 请求参数
type OperateVeinmindAgentParams struct {
	Filter map[string]interface{} `json:"filter"` // 筛选器
	OperationData map[string]interface{} `json:"operation_data"` // 更新||卸载||安装探针指定模块
	SelectFilter map[string]interface{} `json:"select_filter"` // 是否全选&主机ID
}

