// Code generated by workspace-cli-generator. DO NOT EDIT.

package agent_module

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var setRunningModeConfigParams SetRunningModeConfigParams

var SetRunningModeConfigCmd = &cobra.Command{
	Use:   "set_running_mode_config",
	Short: "设置运行模式设置",
	Long:  `设置运行模式设置`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "AgentModuleService.SetRunningModeConfig", setRunningModeConfigParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		SetRunningModeConfigCmd.Flags().BoolVar(&setRunningModeConfigParams.EnableRunningMode, "enable-running-mode", false, "enable_running_mode")
		// filter is object type, use JSON string
		var filterJSON string
		SetRunningModeConfigCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选器 (JSON, e.g. {\"agent_install_plan_id\": [1, 2], \"agent_mem_size\": [\"1GB\"], \"agent_memory_rate\": [\"0.03298633\"], \"...\": \"...\"})")
		// running_mode_config is object type, use JSON string
		var runningModeConfigJSON string
		SetRunningModeConfigCmd.Flags().StringVar(&runningModeConfigJSON, "running-mode-config", "", "running_mode_config (JSON, e.g. {\"enable_monitor\": [\"\"], \"mode\": 0})")
		// select_filter is object type, use JSON string
		var selectFilterJSON string
		SetRunningModeConfigCmd.Flags().StringVar(&selectFilterJSON, "select-filter", "", "是否全选&主机ID (JSON, e.g. {\"select\": [{\"id\": 196}], \"select_all\": true})")
}


// SetRunningModeConfigParams 请求参数
type SetRunningModeConfigParams struct {
	EnableRunningMode bool `json:"enable_running_mode"` // enable_running_mode
	Filter map[string]interface{} `json:"filter"` // 筛选器
	RunningModeConfig map[string]interface{} `json:"running_mode_config"` // running_mode_config
	SelectFilter map[string]interface{} `json:"select_filter"` // 是否全选&主机ID
}

