// Code generated by workspace-cli-generator. DO NOT EDIT.

package agent_module

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var setNetConnCollectEnablementParams SetNetConnCollectEnablementParams

var SetNetConnCollectEnablementCmd = &cobra.Command{
	Use:   "set_net_conn_collect_enablement",
	Short: "设置网络连接采集",
	Long:  `设置网络连接采集`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "AgentModuleService.SetNetConnCollectEnablement", setNetConnCollectEnablementParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		SetNetConnCollectEnablementCmd.Flags().BoolVar(&setNetConnCollectEnablementParams.Enablement, "enablement", false, "是否开启")
		// filter is object type, use JSON string
		var filterJSON string
		SetNetConnCollectEnablementCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选器 (JSON, e.g. {\"agent_install_plan_id\": [1, 2], \"agent_mem_size\": [\"1GB\"], \"agent_memory_rate\": [\"0.03298633\"], \"...\": \"...\"})")
		// select_filter is object type, use JSON string
		var selectFilterJSON string
		SetNetConnCollectEnablementCmd.Flags().StringVar(&selectFilterJSON, "select-filter", "", "是否全选&主机ID (JSON, e.g. {\"select\": [{\"id\": 196}], \"select_all\": true})")
}


// SetNetConnCollectEnablementParams 请求参数
type SetNetConnCollectEnablementParams struct {
	Enablement bool `json:"enablement"` // 是否开启
	Filter map[string]interface{} `json:"filter"` // 筛选器
	SelectFilter map[string]interface{} `json:"select_filter"` // 是否全选&主机ID
}

