// Code generated by workspace-cli-generator. DO NOT EDIT.

package admin_agent

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var deleteModuleParams DeleteModuleParams

var DeleteModuleCmd = &cobra.Command{
	Use:   "delete_module",
	Short: "删除模块",
	Long:  `删除模块`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "AdminAgentService.DeleteModule", deleteModuleParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// filter is object type, use JSON string
		var filterJSON string
		DeleteModuleCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选器 (JSON, e.g. {\"applied\": [\"true\"], \"arch\": [\"amd64\"], \"distributor_os_release\": [\"Ubuntu linux 22.04\"], \"...\": \"...\"})")
		// select_filter is object type, use JSON string
		var selectFilterJSON string
		DeleteModuleCmd.Flags().StringVar(&selectFilterJSON, "select-filter", "", "是否全选&模块ID (JSON, e.g. {\"select\": [{\"id\": 0}], \"select_all\": true})")
}


// DeleteModuleParams 请求参数
type DeleteModuleParams struct {
	Filter map[string]interface{} `json:"filter"` // 筛选器
	SelectFilter map[string]interface{} `json:"select_filter"` // 是否全选&模块ID
}

