// Code generated by workspace-cli-generator. DO NOT EDIT.

package admin_agent

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getModuleListParams GetModuleListParams

var GetModuleListCmd = &cobra.Command{
	Use:   "get_module_list",
	Short: "获取探针模块列表",
	Long:  `获取探针模块列表`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "AdminAgentService.GetModuleList", getModuleListParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// filter is object type, use JSON string
		var filterJSON string
		GetModuleListCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选器 (JSON, e.g. {\"applied\": [\"true\"], \"arch\": [\"amd64\"], \"distributor_os_release\": [\"Ubuntu linux 22.04\"], \"...\": \"...\"})")
		// page is object type, use JSON string
		var pageJSON string
		GetModuleListCmd.Flags().StringVar(&pageJSON, "page", "", "分页器 (JSON, e.g. {\"count\": 20, \"offset\": 0, \"order\": {\"column\": \"level\", \"order\": \"ASC\"}})")
}


// GetModuleListParams 请求参数
type GetModuleListParams struct {
	Filter map[string]interface{} `json:"filter"` // 筛选器
	Page map[string]interface{} `json:"page"` // 分页器
}

