// Code generated by workspace-cli-generator. DO NOT EDIT.

package admin_agent

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var getAgentListParams GetAgentListParams

var GetAgentListCmd = &cobra.Command{
	Use:   "get_agent_list",
	Short: "获取探针列表",
	Long:  `获取探针列表`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "AdminAgentService.GetAgentList", getAgentListParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// filter is object type, use JSON string
		var filterJSON string
		GetAgentListCmd.Flags().StringVar(&filterJSON, "filter", "", "筛选器 (JSON, e.g. {\"agent_install_plan_id\": [1, 2], \"agent_mem_size\": [\"1GB\"], \"agent_memory_rate\": [\"0.03298633\"], \"...\": \"...\"})")
		// page is object type, use JSON string
		var pageJSON string
		GetAgentListCmd.Flags().StringVar(&pageJSON, "page", "", "分页器 (JSON, e.g. {\"count\": 20, \"offset\": 0, \"order\": {\"column\": \"level\", \"order\": \"ASC\"}})")
}


// GetAgentListParams 请求参数
type GetAgentListParams struct {
	Filter map[string]interface{} `json:"filter"` // 筛选器
	Page map[string]interface{} `json:"page"` // 分页器
}

