// Code generated by workspace-cli-generator. DO NOT EDIT.

package baseline_v2

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var createWhitelistParams CreateWhitelistParams

var CreateWhitelistCmd = &cobra.Command{
	Use:   "create_whitelist",
	Short: "生成白名单规则",
	Long:  `生成白名单规则`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "BaselineV2Service.CreateWhitelist", createWhitelistParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		CreateWhitelistCmd.Flags().Float64Var(&createWhitelistParams.SubtaskId, "subtask-id", 0, "根据哪个子任务 ID 加白的")
		// whitelist is object type, use JSON string
		var whitelistJSON string
		CreateWhitelistCmd.Flags().StringVar(&whitelistJSON, "whitelist", "", "whitelist (JSON, e.g. {\"agent_range\": [1, 2, 3], \"builtin_id\": \"1\", \"business_group_range\": [1, 2, 3], \"...\": \"...\"})")
}


// CreateWhitelistParams 请求参数
type CreateWhitelistParams struct {
	SubtaskId float64 `json:"subtask_id"` // 根据哪个子任务 ID 加白的
	Whitelist map[string]interface{} `json:"whitelist"` // whitelist
}

