// Code generated by workspace-cli-generator. DO NOT EDIT.

package baseline_v2

import (
	"fmt"
	"context"

	"github.com/chaitin/workspace-cli/products/cloudwalker/client"
	"github.com/spf13/cobra"
)

var updateLogicParams UpdateLogicParams

var UpdateLogicCmd = &cobra.Command{
	Use:   "update_logic",
	Short: "编辑核查逻辑,目前编辑核查逻辑只能编辑其默认参数(json schema 的 default)",
	Long:  `编辑核查逻辑,目前编辑核查逻辑只能编辑其默认参数(json schema 的 default)`,
	Run: func(cmd *cobra.Command, args []string) {
		cli := client.GetClient()
		var result map[string]interface{}
		err := cli.Call(context.Background(), "BaselineV2Service.UpdateLogic", updateLogicParams, &result)
		if err != nil {
			cmd.PrintErrln("Error:", err)
			return
		}
		fmt.Fprintln(cmd.OutOrStdout(), client.PrintResult(result))
	},
}

func init() {
		// logics is complex type []map[string]interface{}, use JSON string
		var logicsJSON string
		UpdateLogicCmd.Flags().StringVar(&logicsJSON, "logics", "", "要修改的项目 (JSON, e.g. [{\"args\": \"\", \"id\": \"754821f3-06db-455f-9d58-89421216fcf2\"}])")
		UpdateLogicCmd.Flags().StringVar(&updateLogicParams.PkgId, "pkg-id", "", "上传的核查项包, 不传则是修改数据库中已存在的")
}


// UpdateLogicParams 请求参数
type UpdateLogicParams struct {
	Logics []map[string]interface{} `json:"logics"` // 要修改的项目
	PkgId string `json:"pkg_id"` // 上传的核查项包, 不传则是修改数据库中已存在的
}

